// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: count_list.sql

package repository

import (
	"context"
	"database/sql"
)

const countList = `-- name: CountList :one
SELECT COUNT(id) FROM consumers WHERE full_name LIKE ? OR legal_name LIKE ?
`

type CountListParams struct {
	FullName  string         `json:"full_name"`
	LegalName sql.NullString `json:"legal_name"`
}

func (q *Queries) CountList(ctx context.Context, arg *CountListParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countList, arg.FullName, arg.LegalName)
	var count int64
	err := row.Scan(&count)
	return count, err
}
