// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: find_by_id.sql

package repository

import (
	"context"
)

const findByID = `-- name: FindByID :one
SELECT id, nik, full_name, legal_name, birth_place, birth_date, salary, ktp_photo, selfie_photo, created_at, updated_at, updated_by, is_activated, is_activated_at, is_activated_updated_at FROM consumers WHERE id = ? LIMIT 1
`

func (q *Queries) FindByID(ctx context.Context, id int64) (*Consumer, error) {
	row := q.db.QueryRowContext(ctx, findByID, id)
	var i Consumer
	err := row.Scan(
		&i.ID,
		&i.Nik,
		&i.FullName,
		&i.LegalName,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Salary,
		&i.KtpPhoto,
		&i.SelfiePhoto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.IsActivated,
		&i.IsActivatedAt,
		&i.IsActivatedUpdatedAt,
	)
	return &i, err
}
