// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"

	"github.com/shopspring/decimal"
)

type AffiliatedDealer struct {
	ID                   int64  `json:"id"`
	AffiliatedDealerName string `json:"affiliated_dealer_name"`
	// format should be like 0001-01-01 00:00:00Z
	CreatedAt string `json:"created_at"`
	// format should be like 0001-01-01 00:00:00Z
	UpdatedAt   string         `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	IsActivated bool           `json:"is_activated"`
	// format should be like 0001-01-01 00:00:00Z
	IsActivatedAt string `json:"is_activated_at"`
	// format should be like 0001-01-01 00:00:00Z
	IsActivatedUpdatedAt string `json:"is_activated_updated_at"`
}

type Consumer struct {
	ID int64 `json:"id"`
	// Nomor KTP Konsumen
	Nik string `json:"nik"`
	// Nama Lengkap Konsumen
	FullName string `json:"full_name"`
	// Nama Konsumen Di KTP
	LegalName sql.NullString `json:"legal_name"`
	// Tempat lahir konsumen sesuai KTP
	BirthPlace sql.NullString `json:"birth_place"`
	// Tanggal lhir konsumen sesuai KTP
	BirthDate sql.NullTime `json:"birth_date"`
	// Gaji Konsumen
	Salary decimal.NullDecimal `json:"salary"`
	// Foto KTP Konsumen
	KtpPhoto sql.NullString `json:"ktp_photo"`
	// Foto Selfie Konsumen
	SelfiePhoto sql.NullString `json:"selfie_photo"`
	// format should be like 0001-01-01 00:00:00Z
	CreatedAt string `json:"created_at"`
	// format should be like 0001-01-01 00:00:00Z
	UpdatedAt   string         `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	IsActivated bool           `json:"is_activated"`
	// format should be like 0001-01-01 00:00:00Z
	IsActivatedAt string `json:"is_activated_at"`
	// format should be like 0001-01-01 00:00:00Z
	IsActivatedUpdatedAt string `json:"is_activated_updated_at"`
}

type ConsumerLoanLimit struct {
	ID         int64           `json:"id"`
	ConsumerID int64           `json:"consumer_id"`
	Tenor      int16           `json:"tenor"`
	Amount     decimal.Decimal `json:"amount"`
	// format should be like 0001-01-01 00:00:00Z
	CreatedAt string `json:"created_at"`
	// format should be like 0001-01-01 00:00:00Z
	UpdatedAt string         `json:"updated_at"`
	UpdatedBy sql.NullString `json:"updated_by"`
}
