global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [prometheus:9090"]

  - job_name: "system"
    static_configs:
      - targets: [node_exporter:9101"]

  - job_name: "backends"
    static_configs:
      - targets: ["backend_1:8880"]
      - targets: ["backend_2:8880"]
      - targets: ["backend_3:8880"]
