// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: count_list.sql

package repository

import (
	"context"
)

const countList = `-- name: CountList :one
SELECT COUNT(id) FROM consumer_transactions WHERE consumer_id = ?
`

func (q *Queries) CountList(ctx context.Context, consumerID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countList, consumerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
