// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: create_affiliated_dealer.sql

package repository

import (
	"context"
	"database/sql"
)

const createAffiliatedDealer = `-- name: CreateAffiliatedDealer :execresult
INSERT INTO affiliated_dealers (
    affiliated_dealer_name,
    created_at
) VALUES (
    ?, ?
)
`

type CreateAffiliatedDealerParams struct {
	AffiliatedDealerName string `json:"affiliated_dealer_name"`
	CreatedAt            string `json:"created_at"`
}

func (q *Queries) CreateAffiliatedDealer(ctx context.Context, arg *CreateAffiliatedDealerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAffiliatedDealer, arg.AffiliatedDealerName, arg.CreatedAt)
}
