// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: find_by_id.sql

package repository

import (
	"context"
)

const findByID = `-- name: FindByID :one
SELECT id, consumer_id, contract_number, admin_fee_amount, installment_amount, otr_amount, interest_rate, transaction_date, affiliated_dealer_id, created_at, updated_at, updated_by FROM consumer_transactions WHERE id = ? LIMIT 1
`

func (q *Queries) FindByID(ctx context.Context, id int64) (*ConsumerTransaction, error) {
	row := q.db.QueryRowContext(ctx, findByID, id)
	var i ConsumerTransaction
	err := row.Scan(
		&i.ID,
		&i.ConsumerID,
		&i.ContractNumber,
		&i.AdminFeeAmount,
		&i.InstallmentAmount,
		&i.OtrAmount,
		&i.InterestRate,
		&i.TransactionDate,
		&i.AffiliatedDealerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return &i, err
}
