// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"

	"github.com/shopspring/decimal"
)

type AffiliatedDealer struct {
	ID                   int64  `json:"id"`
	AffiliatedDealerName string `json:"affiliated_dealer_name"`
	// format should be like 0001-01-01 00:00:00Z
	CreatedAt string `json:"created_at"`
	// format should be like 0001-01-01 00:00:00Z
	UpdatedAt   string         `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	IsActivated bool           `json:"is_activated"`
	// format should be like 0001-01-01 00:00:00Z
	IsActivatedAt string `json:"is_activated_at"`
	// format should be like 0001-01-01 00:00:00Z
	IsActivatedUpdatedAt string `json:"is_activated_updated_at"`
}

type Consumer struct {
	ID int64 `json:"id"`
	// Nomor KTP Konsumen
	Nik string `json:"nik"`
	// Nama Lengkap Konsumen
	FullName string `json:"full_name"`
	// Nama Konsumen Di KTP
	LegalName sql.NullString `json:"legal_name"`
	// Tempat lahir konsumen sesuai KTP
	BirthPlace sql.NullString `json:"birth_place"`
	// Tanggal lhir konsumen sesuai KTP
	BirthDate sql.NullTime `json:"birth_date"`
	// Gaji Konsumen
	Salary decimal.NullDecimal `json:"salary"`
	// Foto KTP Konsumen
	KtpPhoto sql.NullString `json:"ktp_photo"`
	// Foto Selfie Konsumen
	SelfiePhoto sql.NullString `json:"selfie_photo"`
	// format should be like 0001-01-01 00:00:00Z
	CreatedAt string `json:"created_at"`
	// format should be like 0001-01-01 00:00:00Z
	UpdatedAt   string         `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	IsActivated bool           `json:"is_activated"`
	// format should be like 0001-01-01 00:00:00Z
	IsActivatedAt string `json:"is_activated_at"`
	// format should be like 0001-01-01 00:00:00Z
	IsActivatedUpdatedAt string `json:"is_activated_updated_at"`
}

type ConsumerTransaction struct {
	ID         int64 `json:"id"`
	ConsumerID int64 `json:"consumer_id"`
	// Nomor Kontrak untuk setiap transaksi konsumen
	ContractNumber string `json:"contract_number"`
	// Angka fee admin
	AdminFeeAmount decimal.NullDecimal `json:"admin_fee_amount"`
	// Angka jumlah cicilan
	InstallmentAmount decimal.NullDecimal `json:"installment_amount"`
	// Angka On The Road transaksi barang
	OtrAmount decimal.NullDecimal `json:"otr_amount"`
	// angka bunga yang ditangihkan setiap transaksi
	InterestRate decimal.NullDecimal `json:"interest_rate"`
	// format should be like 0001-01-01 00:00:00Z
	TransactionDate    string `json:"transaction_date"`
	AffiliatedDealerID int64  `json:"affiliated_dealer_id"`
	// format should be like 0001-01-01 00:00:00Z
	CreatedAt string `json:"created_at"`
	// format should be like 0001-01-01 00:00:00Z
	UpdatedAt string         `json:"updated_at"`
	UpdatedBy sql.NullString `json:"updated_by"`
}
