// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/shopspring/decimal"
)

const update = `-- name: Update :exec
UPDATE consumer_transactions
SET
    admin_fee_amount = COALESCE(?, admin_fee_amount),
    installment_amount = COALESCE(?, installment_amount),
    otr_amount = COALESCE(?, otr_amount),
    interest_rate = COALESCE(?, interest_rate),
    updated_at = COALESCE(?, updated_at),
    updated_by = COALESCE(?, updated_by)
WHERE
    id = ?
`

type UpdateParams struct {
	AdminFeeAmount    decimal.NullDecimal `json:"admin_fee_amount"`
	InstallmentAmount decimal.NullDecimal `json:"installment_amount"`
	OtrAmount         decimal.NullDecimal `json:"otr_amount"`
	InterestRate      decimal.NullDecimal `json:"interest_rate"`
	UpdatedAt         sql.NullString      `json:"updated_at"`
	UpdatedBy         sql.NullString      `json:"updated_by"`
	ID                int64               `json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg *UpdateParams) error {
	_, err := q.db.ExecContext(ctx, update,
		arg.AdminFeeAmount,
		arg.InstallmentAmount,
		arg.OtrAmount,
		arg.InterestRate,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
