// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: find_by_id.sql

package repository

import (
	"context"
)

const findByID = `-- name: FindByID :one
SELECT id, consumer_id, tenor, amount, created_at, updated_at, updated_by FROM consumer_loan_limits WHERE id = ? LIMIT 1
`

func (q *Queries) FindByID(ctx context.Context, id int64) (*ConsumerLoanLimit, error) {
	row := q.db.QueryRowContext(ctx, findByID, id)
	var i ConsumerLoanLimit
	err := row.Scan(
		&i.ID,
		&i.ConsumerID,
		&i.Tenor,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return &i, err
}
