// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: list.sql

package repository

import (
	"context"
)

const list = `-- name: List :many
SELECT id, consumer_id, tenor, amount, created_at, updated_at, updated_by FROM consumer_loan_limits WHERE consumer_id = ?
ORDER BY created_at DESC
LIMIT ?
OFFSET ?
`

type ListParams struct {
	ConsumerID int64 `json:"consumer_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) List(ctx context.Context, arg *ListParams) ([]*ConsumerLoanLimit, error) {
	rows, err := q.db.QueryContext(ctx, list, arg.ConsumerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ConsumerLoanLimit{}
	for rows.Next() {
		var i ConsumerLoanLimit
		if err := rows.Scan(
			&i.ID,
			&i.ConsumerID,
			&i.Tenor,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
