// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/shopspring/decimal"
)

const update = `-- name: Update :exec
UPDATE consumer_loan_limits
SET
    tenor = COALESCE(?, tenor),
    amount = COALESCE(?, amount),
    updated_at = COALESCE(?, updated_at),
    updated_by = COALESCE(?, updated_by)
WHERE
    id = ?
`

type UpdateParams struct {
	Tenor     sql.NullInt16       `json:"tenor"`
	Amount    decimal.NullDecimal `json:"amount"`
	UpdatedAt sql.NullString      `json:"updated_at"`
	UpdatedBy sql.NullString      `json:"updated_by"`
	ID        int64               `json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg *UpdateParams) error {
	_, err := q.db.ExecContext(ctx, update,
		arg.Tenor,
		arg.Amount,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
