// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: find_by_id.sql

package repository

import (
	"context"
)

const findByID = `-- name: FindByID :one
SELECT id, affiliated_dealer_name, created_at, updated_at, updated_by, is_activated, is_activated_at, is_activated_updated_at FROM affiliated_dealers WHERE id = ? LIMIT 1
`

func (q *Queries) FindByID(ctx context.Context, id int64) (*AffiliatedDealer, error) {
	row := q.db.QueryRowContext(ctx, findByID, id)
	var i AffiliatedDealer
	err := row.Scan(
		&i.ID,
		&i.AffiliatedDealerName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.IsActivated,
		&i.IsActivatedAt,
		&i.IsActivatedUpdatedAt,
	)
	return &i, err
}
